<?php

namespace App\Http\Requests\API;

use App\Http\Requests\BaseRequest;
use App\Rules\ValidateSignCallbackTransfer;

class CallbackTransferRequest extends BaseRequest
{

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return array_merge(parent::rules(), [
            'trans_id' => 'required|exists:history_transfers,trans_id',
            'system_id' => 'required|exists:history_transfers,system_id',
            'sign' => [
                'required',
                new ValidateSignCallbackTransfer($this->parameters())
            ]
        ]);
    }

    public function parameters()
    {
        return [
            'trans_id' => $this->input('trans_id'),
            'system_id' => $this->input('system_id'),
            'sign' => $this->input('sign'),
        ]; // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return [
            'trans_id' => 'mã giao dịch',
            'system_id' => 'mã đối soát giao dịch',
            'sign' => 'Chữ ký'
        ];
    }

}
