<?php

namespace App\Http\Requests\Auth;

use App\Http\Requests\BaseRequest;

class ApiRequest extends BaseRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'token' => 'required|exists:banks,token'
        ];
    }

    public function parameters()
    {
        return array_merge(parent::parameters(), [
            'token' => $this->input('token'),
            'account_number' => $this->input('account_number')
        ]);
    }

    public function messages()
    {
        return array_merge(parent::messages(), [
            'token.required' => 'Token không được để trống!',
            'token.exists' => 'Token không tồn tại hoặc đã hết hạn!',
        ]); // TODO: Change the autogenerated stub
    }
}
